### ISSUE TITLE
LevelZ on Server using localconfig

### ISSUE THREAD

**Issue by OFVGuest** [Globox1997/LevelZ#102] opened 2022-01-25 20:39 UTC
While playing in a server, levelz server config does not overwrite the local config.

**Comment by Icyvexen** [comment] 2022-01-26 06:16
I can also confirm this to be the case

How to reproduce: 
- Set local config to 0
- Set dedicated server config to any not-0 value for multiplicator

It will show you only need 50 xp to the next level, and get a point at the 50 xp versus the much larger actual value

I had played for a few dozen hours having adjusted the XP rates thinking it had updated only to realize at level 100 that the math showed it was not updated correctly.

For my instance, the server AND the client were on the same machine, but a dedicated server instance was used to run the server. This behavior was also noted by those connecting to the server outside the local network.

Used Valhelsia: Enhanced Vanilla 1.0.5

**Comment by Globox1997** [comment] 2022-05-06 12:23
[levelz-1.3.1.zip](https://github.com/Globox1997/LevelZ/files/8639924/levelz-1.3.1.zip)
Can you guys test this? (unzip the file)
The client doesn't override server settings, the issue is here that the level system takes client input which leads to this issue

**Comment by Coyote21** [comment] 2022-05-09 04:28
Another confirmation, same issue.
Also tested the 1.3.1 version posted above. Made no difference, although I only tested by changing the maxLevel in the client version of levelz.json5 to 20 (left the server version at 40) and restarted both server and client, just to be sure. Client and server are on separate machines.

In-game GUI showed only 20 levels available.

Current work around is to just send the correct levelz.json5 config file to all the clients, fortunately they know how/where to put the config file.

**Comment by Globox1997** [comment] 2022-05-10 09:28
[levelz-1.3.1.zip](https://github.com/Globox1997/LevelZ/files/8660240/levelz-1.3.1.zip)
That should now definitely work :D

**Comment by Coyote21** [comment] 2022-05-11 14:27
Only tested maxLevel again, but yes, this version now works.

Been working with this mod a bit now and just want to also say, Great Work! I'm really enjoying it, Thanks.

**Comment by Globox1997** [comment] 2022-06-02 18:56
This is fixed with the latest update

**Closed as completed by Globox1997** 2022-06-02 18:56 UTC

**Comment by Kelo111** [comment] 2022-08-10 09:37
what about 1.19 ???

**Comment by Globox1997** [comment] 2022-08-10 10:13
@Kelo111 this is fixed in 1.19 too

**Comment by Kelo111** [comment] 2022-08-11 09:23
for me doesnt work
i have an aternos server and i edit the config it doesnt do anything
@Globox1997

**Comment by Globox1997** [comment] 2022-08-12 07:24
do you edit the config on the server or the client while playing on the server?

**Comment by Kelo111** [comment] 2022-08-12 12:32
@Globox1997 i edit server config

**Comment by Globox1997** [comment] 2022-08-19 12:06
Are you talking about all settings or specific ones?

**Comment by Kelo111** [comment] 2022-08-19 14:51
@Globox1997 all of them
