### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Rogenar** [Globox1997/LevelZ#276] opened 2023-06-11 13:55 UTC
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.21

### Mod Version

1.4.9

### Describe the Issue

Game crashes on farm tools.

### latest.log

![ss2](https://github.com/Globox1997/LevelZ/assets/122460325/95c2f635-3b8e-4111-9939-cf4e80250aaa)
[latest.log](https://github.com/Globox1997/LevelZ/files/11714759/latest.log)
[rei.log](https://github.com/Globox1997/LevelZ/files/11714760/rei.log)
[crash-2023-06-11_16.48.23-client.txt](https://github.com/Globox1997/LevelZ/files/11714761/crash-2023-06-11_16.48.23-client.txt)
[rei-issues.log](https://github.com/Globox1997/LevelZ/files/11714762/rei-issues.log)

### Do you use any other mods except the required ones?

Yes, I am using other mods.

**Comment by xR4YM0ND** [comment] 2023-09-14 20:00
You need a special -jvm flag 

Or use the Global Minecraft Launcher or another Launcher like Modrinth / Curseforge

**Comment by xR4YM0ND** [comment] 2023-09-14 20:40
Duplicate of: https://github.com/Globox1997/LevelZ/issues/255

**Comment by xR4YM0ND** [comment] 2023-09-14 20:40
Try these two jvm flags:
-Duser.language=en -Duser.country=US

**Closed as completed by xR4YM0ND** 2023-09-14 20:40 UTC
