### ISSUE TITLE
[1.18.1] Crash with SurvivalPlus Lightsabers when hovering lightsaber in inventory to view tooltip.

### ISSUE THREAD

**Issue by lizfinite** [Globox1997/LevelZ#81] opened 2021-12-31 13:56 UTC
Not sure if this is something to be fixed on your end, or theirs but I'll open one here just in case.

Crash Log: [https://paste.ee/p/Klhil](https://paste.ee/p/Klhil)

**Mods:**
- fabric-api-0.45.0+1.18
- cloth-config-6.1.48-fabric
- levelz-1.1.4
- modmenu-3.0.1
- SurvivalPlus-Fabric-1.18.1-0.1.6
- SurvivalPlus-Lightsabers-Fabric-1.18.1-0.1.6

**Steps to reproduce:**
1. Enter world
2. Give any lightsaber
3. Hover within inventory

**Comment by coolsimulations** [comment] 2022-01-21 22:49
This is definitely an issue with LevelZ. The problem is that Lightsabers are included in the Sword Fabric Tool Tag but since the Lightsaber isn't an instance of ToolItem, it cannot be cast and thus crashes. The crash would occur with any other kind of tool/sword mod that doesn't extend the ToolItem class.

My crash report [crash-2022-01-22_08.43.11-client.txt](https://github.com/Globox1997/LevelZ/files/7916998/crash-2022-01-22_08.43.11-client.txt)

Where it crashes:
https://github.com/Globox1997/LevelZ/blob/d662fe456a015e1be78928ad8a37925b3ca25c29/src/main/java/net/levelz/mixin/item/ItemStackClientMixin.java#L184-L190

A simple fix would be to check if the item is an instance of ToolItem rather than to straight up cast.

**Comment by Globox1997** [comment] 2022-02-19 15:58
Fixed with [https://github.com/Globox1997/LevelZ/commit/ccf93b863654980dd6176695bc315957171d728d](https://github.com/Globox1997/LevelZ/commit/ccf93b863654980dd6176695bc315957171d728d)

**Closed as completed by Globox1997** 2022-02-19 15:58 UTC
