### ISSUE TITLE
MC Dungeons Weapons Tooltip Crash

### ISSUE THREAD

**Issue by KxmischesDomi** [Globox1997/LevelZ#20] opened 2021-09-04 15:35 UTC
The game crashes when I hover over some items of the MCDW Mod in the creative gui.
I tested it without LevelZ and then everything works perfectly fine.

Crashlog: https://pastebin.com/v0e34w3r

**Comment by Gengarxw** [comment] 2021-09-08 02:01
Does the same with MC Dungeons Armors and MC Story Mode Armors.

**Comment by Globox1997** [comment] 2021-09-09 15:26
@Gengarxw can you send a crash log please

**Comment by OxcydePlays** [comment] 2021-09-16 04:26
Slightly related issue, but is caused by a different set of actions. The game crashes when accessing the gui for LevelZ while actively holding MC Dungeons weapons tagged as "spear". Tested out other class weapons from the same mod, but the gui works well and the game doesn't crash.

Crashlog: https://pastebin.com/iC7riPBB

**Comment by Globox1997** [comment] 2021-09-17 20:00
Thanks for the log, fixed with [https://github.com/Globox1997/LevelZ/commit/6276f955bbd92eeee936fe8ca399dffe90da1653](https://github.com/Globox1997/LevelZ/commit/6276f955bbd92eeee936fe8ca399dffe90da1653)
If you have a log for the armor mod, reopen this issue :)

**Closed by Globox1997** 2021-09-17 20:00 UTC
