### ISSUE TITLE
Game crashes when I interact with a Crafting Table

### ISSUE THREAD

**Issue by Tolemor** [Globox1997/LevelZ#264] opened 2023-04-20 21:45 UTC
I saw another post where the poster had the same issue. They were asked if they are from Turkey. Does that have anything to do with it? I can't make progress if I can't craft. This is a major flaw.
[crash-2023-04-21_00.42.02-client.txt](https://github.com/Globox1997/LevelZ/files/11290672/crash-2023-04-21_00.42.02-client.txt)

**Comment by Globox1997** [comment] 2023-04-25 08:10
Yes this has something to do with the compiler language which is somehow based on the platform language.
In the crashlog you can see a method can not find the SMITHING skill cause it has some points above the letters.

**Comment by lunight13** [comment] 2023-09-04 20:56
happens to me as well, also from Turkey. :')

**Comment by xR4YM0ND** [comment] 2023-09-14 20:39
Try these two jvm flags:
-Duser.language=en -Duser.country=US

**Comment by xR4YM0ND** [comment] 2023-09-14 20:39
Duplicate of: https://github.com/Globox1997/LevelZ/issues/255

**Closed as completed** 2023-09-14 20:40 UTC
