### ISSUE TITLE
Added left click limit to custom items and add multi-skill requirement support.

### ISSUE THREAD

**Issue by PIPILAN** [Globox1997/LevelZ#151] opened 2022-06-15 07:42 UTC
1.Want to add left click limit to custom items, now only right click limit.I guess maybe just cancel the event? I don't know. It's just a guess

2.Can you add multi-skill requirement support?  For example, I want to add two skill requirements for farming and strength to an item.

**Comment by Globox1997** [comment] 2022-06-15 11:29
I could add a setting to disable the left click mechanic of items but that doesn't feel good in the vanilla view in my opinion.
The issue is, it would disable the left click mechanic of all locked items.

The second request is the same as [https://github.com/Globox1997/LevelZ/issues/129](https://github.com/Globox1997/LevelZ/issues/129), will be a future feature but not sure when I will get to it

**Comment by PIPILAN** [comment] 2022-06-15 11:33
> I could add a setting to disable the left click mechanic of items but that doesn't feel good in the vanilla view in my opinion. The issue is, it would disable the left click mechanic of all locked items.
> 
> The second request is the same as #129, will be a future feature but not sure when I will get to it

Can't limit a single item left click? don't know how to program and I don't know how hard this is, so forgive me if I have offended you.

**Comment by PIPILAN** [comment] 2022-06-15 11:35
Or it can only apply to custom items, which is really important, otherwise my restrictions on weapons and various other items won't work

**Comment by Globox1997** [comment] 2022-06-15 11:41
about what kind of weapons are you talking? cause the custom item restriction should already work

**Comment by PIPILAN** [comment] 2022-06-15 11:45
> about what kind of weapons are you talking? cause the custom item restriction should already work

Some special weapons, such as spears.The [Impaled](https://www.curseforge.com/minecraft/mc-mods/impaled) mod can also limit right-click casting, not left-click attacks.

**Comment by PIPILAN** [comment] 2022-06-15 12:07
> The [Impaled](https://www.curseforge.com/minecraft/mc-mods/impaled) mod can also limit right-click casting, not left-click attacks.

Just like this.
![test](https://user-images.githubusercontent.com/38380796/173823262-e0840228-4784-4579-bafe-a2ecefbdcd69.gif)

**Comment by Globox1997** [comment] 2022-06-16 13:40
which levelz version do you use?

**Comment by PIPILAN** [comment] 2022-06-16 13:42
1.18.2 fabric 1.3.3

**Comment by Globox1997** [comment] 2022-06-16 17:54
Fixed with [https://github.com/Globox1997/LevelZ/commit/60020dbf391341860fcc9f4856e76bcf971d246b](https://github.com/Globox1997/LevelZ/commit/60020dbf391341860fcc9f4856e76bcf971d246b)
Out of time reasons I only work on the latest version, so this is for 1.19

**Closed as completed by Globox1997** 2022-06-16 17:54 UTC

**Comment by PIPILAN** [comment] 2022-06-17 01:27
I am very sad to hear this, I am using version 1.18.2 to make the modpack, this fix doesn't work for me. :(
