### ISSUE TITLE
Alchemy issue

### ISSUE THREAD

**Issue by Herzogue93** [Globox1997/LevelZ#29] opened 2021-09-14 18:59 UTC
I have an issue when leveling up the Alchemy skill.
Once I start leveling it up it struggles applying the double effect and starts shaking ( like changing FOV non-stop ) the whole picture.
Can apply a video if needed.

**Comment by Globox1997** [comment] 2021-09-14 19:22
Do you use the latest mod version?
Does it only happen when max skilled at alchemy skill?
Video would be neat :)

**Comment by spycheeto1** [comment] 2021-09-15 17:50
It happens the moment you get alchemy 1. Did you secretly add this as a troll and its meant to be an actual feature? lmao

**Comment by Globox1997** [comment] 2021-09-15 19:46
Definitely not XD 
does it happen when levelz is only installed?

**Comment by spycheeto1** [comment] 2021-09-15 21:46
I figured out the cause to be the MC Dungeons Armor mod. Basically when getting alchemy 1 it gave you all the enchants from that mod for some weird reason.

**Comment by Globox1997** [comment] 2021-09-16 08:48
That is odd, on what item does these enchants get applied to?

**Comment by noncom** [comment] 2021-09-16 11:49
Same case as mine, it seems: https://github.com/Globox1997/LevelZ/issues/27

**Comment by OxcydePlays** [comment] 2021-09-16 11:55
I just got the same issue as well.

Adding on the MC Adventures mod observation, I think spycheeto1 just meant that any additional enchantment that the MCA mod has were given to the character, not necessarily on a particular equipt. In my case, I'm only wearing a full diamond set which has vanilla enchantments save for one (Recycler I) on my boots. I tried taking that off but I'm still getting constant poisoning. No random enchantment got suddenly added to any of the equipts.

Also, commenting on the issue itself, aside from the poison effect, I can only see that I'm getting buffed with Luck and afflicted with Bad Luck at the same time, for around 5 seconds, so long as I have >4 HP. Not sure if I'm getting other buffs/debuffs as I don't see any other icons popping out aside from those two.

**Comment by noncom** [comment] 2021-09-16 11:57
Will check if removing MC Dungeon* mods gonna make the behavior disappear (much later in today).

**Comment by OxcydePlays** [comment] 2021-09-16 12:25
> UPDATE: wait, did you mean MC Dungeons or MC Adventures now? I don't have MC Adventures, and I believe there's no such mod in existence (can't find on CF), but instead I have Adventurez installed, but that's different.

My bad. I meant Dungeons. AdventureZ is good.

**Comment by Globox1997** [comment] 2021-09-16 13:48
To make it clear, if only LevelZ and this MC Dungeons (which one exactly?) mod is installed + their dependencies, this bug occurs?

**Comment by noncom** [comment] 2021-09-16 14:50
So yes, confirmed. Only LevelZ + MC Dungeons Armors are installed on Fabric 0.11.6 the bug happens.

Even a single level in Alchemy starts beating you regularly. Removing MCDA and re-entering the world makes the bug go away.

ALSO: I have just noticed that the amount of total hearts is also reduced to 3 (three) and healing above approx 50% of this calls the damaging effect again.

**Comment by OxcydePlays** [comment] 2021-09-17 00:27
Good thing it's just the armors. I don't use them anyway.
 
> ALSO: I have just noticed that the amount of total hearts is also reduced to 3 (three). Probably the effect of only having 3 hearts at start is something natural for LevelZ progression mechanics.
Yeah, that's how it goes. It's harsh, but I like it.

**Comment by spycheeto1** [comment] 2021-09-17 18:37
Like some before be have stated, it basically gives the player random enchants without actually applying them on any piece of equipment or armor. I also believe that its not just a MC Dungeons Armour thing because I've had frost walker turn on sometimes (randomly), and my friends have experience soul speed. What is visible is when you get applied random enchants applied to your character and all at lowest level. (it possibly gives you other enchants as well such as prot but that's something we wouldn't notice)

But yeah, in short leveling up alchemy seems to cause an issue with enchantments being applied to your character, not equipment, making there be no way to remove them. We thought it was a secret curse that came with the mod, but as we learned later, all the curses were simply other enchantments from different mods/vanilla.

**Comment by spycheeto1** [comment] 2021-09-23 04:36
Any updates toward resolving the issue?

**Comment by Globox1997** [comment] 2021-09-23 20:05
I already checked the code of the dungeons armor mod and I couldn't find anything which can cause this behavior

**Comment by noncom** [comment] 2021-09-23 21:22
But does it repeat for you in such a setup? Maybe it can be repeated in dev environment and debugged?

**Comment by Globox1997** [comment] 2021-09-24 06:58
After some debugging I found the issue:
Mcda (and maybe more of chronos mods) tick every tick (so 20 times a second) through all his special item settings and checks if the player has the gear on + their specific enchantings - which is basically a cheap solution and not performance friendly. For this reason I opened this issue [https://github.com/chronosacaria/MCDungeonsArmors/issues/17](https://github.com/chronosacaria/MCDungeonsArmors/issues/17). I fixed it with [https://github.com/Globox1997/LevelZ/commit/e05c89806cdb9a30c646ea75e9e3b5090de3fe5a](https://github.com/Globox1997/LevelZ/commit/e05c89806cdb9a30c646ea75e9e3b5090de3fe5a)

**Closed by Globox1997** 2021-09-24 06:58 UTC

**Comment by noncom** [comment] 2021-09-24 21:21
Wow, I see, yeah they're doing those unnecessary updates for no good. I hope they fix that. Glad that the workaround for LevelZ turned out to be so simple here though!
