### ISSUE TITLE
Crash occurs at clicking to crafting table

### ISSUE THREAD

**Issue by FatihAlper** [Globox1997/LevelZ#295] opened 2023-08-16 04:50 UTC
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.22

### Mod Version

1.4.10

### Describe the Issue

Crash occurs while right clicking to crafting table. Same crash occurs when using simply swords mod when scrolling through inventory at simply swords tab. 

### latest.log

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2023-08-16 07:45:57
Description: Unexpected error

java.lang.IllegalArgumentException: No enum constant net.levelz.stats.Skill.SMİTHİNG
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at net.levelz.stats.Skill.valueOf(Skill.java:9)
	at net.levelz.stats.PlayerStatsManager.getLevel(PlayerStatsManager.java:129)
	at net.levelz.stats.PlayerStatsManager.playerLevelisHighEnough(PlayerStatsManager.java:208)
	at net.minecraft.class_2304.handler$bin011$levelz$onUseMixin(class_2304.java:534)
	at net.minecraft.class_2304.method_9534(class_2304.java)
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:1133)
	at net.minecraft.class_636.method_41934(class_636.java:347)
	at net.minecraft.class_636.method_41933(class_636.java:324)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2896(class_636.java:323)
	at net.minecraft.class_310.method_1583(class_310.java:1802)
	at net.minecraft.class_310.method_1508(class_310.java:2052)
	at net.minecraft.class_310.method_1574(class_310.java:1883)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at net.levelz.stats.Skill.valueOf(Skill.java:9)
	at net.levelz.stats.PlayerStatsManager.getLevel(PlayerStatsManager.java:129)
	at net.levelz.stats.PlayerStatsManager.playerLevelisHighEnough(PlayerStatsManager.java:208)
	at net.minecraft.class_2304.handler$bin011$levelz$onUseMixin(class_2304.java:534)
	at net.minecraft.class_2304.method_9534(class_2304.java)
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:1133)
	at net.minecraft.class_636.method_41934(class_636.java:347)
	at net.minecraft.class_636.method_41933(class_636.java:324)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2896(class_636.java:323)
	at net.minecraft.class_310.method_1583(class_310.java:1802)
	at net.minecraft.class_310.method_1508(class_310.java:2052)

-- Affected level --
Details:
	All players: 1 total; [class_746['FatihAlper'/539, l='ClientLevel', x=32.25, y=87.00, z=-2.57]]
	Chunk stats: 1024, 489
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,91,-16), Section: (at 0,11,0 in 1,5,-1; chunk contains blocks 16,-64,-16 to 31,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 17987 game time, 17987 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, file/Bare+Bones+1.20 (1).zip

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 442398888 bytes (421 MiB) / 1006632960 bytes (960 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
	Identifier: Intel64 Family 6 Model 78 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 1.99
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 520
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x1916
	Graphics card #0 versionInfo: DriverVersion=30.0.101.1338
	Graphics card #1 name: Radeon (TM) R5 M430
	Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #1 VRAM (MB): 2048.00
	Graphics card #1 deviceId: 0x6660
	Graphics card #1 versionInfo: DriverVersion=27.20.20904.4000
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 9977.81
	Virtual memory used (MB): 5281.66
	Swap memory total (MB): 1920.00
	Swap memory used (MB): 59.98
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.8.0
		appleskin: AppleSkin 2.5.0+mc1.20
		architectury: Architectury 9.1.12
		balm-fabric: Balm 7.0.7
		bettercombat: Better Combat 1.7.3+1.20.1
		cardinal-components: Cardinal Components API 5.2.2
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-block: Cardinal Components API (blocks) 5.2.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			cardinal-components-item: Cardinal Components API (items) 5.2.2
			cardinal-components-level: Cardinal Components API (world saves) 5.2.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		doapi: Lets Do Api 1.2.6
			terraform-wood-api-v1: Terraform Wood API (v1) 7.0.1
		enhancermod: Enhancer Mod 1.4.0.1-1.20.1
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.9
		fabric-api: Fabric API 0.87.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.2.2+1e61dba177
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.2+6bdb2ed077
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.2+6bdb2ed077
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.34+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.0+cdf060b277
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabricloader: Fabric Loader 0.14.22
		friendsandfoes: Friends&Foes 1.9.3
		indium: Indium 1.0.24+mc1.20.1
		java: OpenJDK 64-Bit Server VM 17
		jobsaddon: JobsAddon 1.1.2
		krypton: Krypton 0.2.3
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		lazydfu: LazyDFU 0.1.3
		levelz: LevelZ 1.4.10
		libz: LibZ 1.0.1
		lithium: Lithium 0.11.2
		map_atlases: Map Atlases 2.6.0
		medievalweapons: Medieval Weapons 1.4.6
		minecraft: Minecraft 1.20.1
		modmenu: Mod Menu 7.2.1
		numismatic-overhaul: Numismatic Overhaul 0.2.9+1.20
			stacc: Stacc 1.5.3-pre.1
		owo: oωo 0.11.1+1.20
			blue_endless_jankson: jankson 1.2.2
		player-animator: Player Animator 1.0.2-rc1+1.20
		reeses-sodium-options: Reese's Sodium Options 1.6.4+mc1.20.1-build.94
		sodium: Sodium 0.5.1
		sodium-extra: Sodium Extra 0.5.1+mc1.20.1-build.112
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		travelersbackpack: Traveler's Backpack 1.20.1-9.1.2
		vinery: Vinery 1.4.4
		voicechat: Simple Voice Chat 1.20.1-2.4.19
		waystones: Waystones 14.0.1
	Launched Version: fabric-loader-0.14.22-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Radeon (TM) R5 M430 GL version 3.2.14830 Core Profile Forward-Compatible No Error Context 21.09.04.04 27.20.20904.4000, ATI Technologies Inc.
	Window size: 1366x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, file/Bare+Bones+1.20 (1).zip
	Current Language: tr_tr
	CPU: 4x Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz

### Do you use any other mods except the required ones?

specified in log file

**Comment by xR4YM0ND** [comment] 2023-09-14 20:09
Duplicate of: https://github.com/Globox1997/LevelZ/issues/276

**Closed as completed** 2023-09-14 20:09 UTC

**Comment by xR4YM0ND** [comment] 2023-09-14 20:41
Try these two jvm flags:
-Duser.language=en -Duser.country=US
