### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Rogenar** [Globox1997/LevelZ#288] opened 2023-07-24 14:28 UTC
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.21

### Mod Version

1.4.10

### Describe the Issue

The game crashes when I pick up the elytra.
![sss1](https://github.com/Globox1997/LevelZ/assets/122460325/8f65c868-1fc8-4bbd-bdae-cf8e4bd07ab7)

### latest.log

[latest.log](https://github.com/Globox1997/LevelZ/files/12146932/latest.log)
[rei.log](https://github.com/Globox1997/LevelZ/files/12146945/rei.log)
[rei-issues.log](https://github.com/Globox1997/LevelZ/files/12146954/rei-issues.log)
[crash-2023-07-24_17.24.15-client.txt](https://github.com/Globox1997/LevelZ/files/12146955/crash-2023-07-24_17.24.15-client.txt)

### Do you use any other mods except the required ones?

Yes, I am using other mods.

**Comment by Rogenar** [comment] 2023-08-07 13:16
@Globox1997 Will there be an update to fix this issue?

**Comment by FatihAlper** [comment] 2023-08-16 05:14
same issue here with simply swords mod

**Comment by Rogenar** [comment] 2023-08-16 12:29
so this error is caused by simply sword mode?

**Comment by FatihAlper** [comment] 2023-08-16 21:19
not really. its because of levelz mod poorly written. if you test it out alone it will crash too

**Comment by Rogenar** [comment] 2023-08-16 21:50
I personally reported this problem to the mod's producer by going to the discord servers, but he said that it would not fix the problem. The creator of the mod responds very late. Since it didn't solve the problem, I removed the mod from my modpack and I don't recommend it to anyone. I recommend puferfish skills and simply skills mods instead of this mod.

**Comment by xR4YM0ND** [comment] 2023-09-14 20:00
You need a special -jvm flag

Or use the Global Minecraft Launcher or another Launcher like Modrinth / Curseforge

**Comment by xR4YM0ND** [comment] 2023-09-14 20:01
Duplicate of: https://github.com/Globox1997/LevelZ/issues/276

**Closed as completed** 2023-09-14 20:09 UTC

**Comment by xR4YM0ND** [comment] 2023-09-14 20:41
Try these two jvm flags:
-Duser.language=en -Duser.country=US
